In [ ]:
array=[1,2,3,4,5,6,7,8,9]
array

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr1[2:5]=10
xyz=arr1[2:6]
xyz

array([10, 10, 10,  6])

In [ ]:
arr1[4]=5
arr1

array([ 1,  2, 10, 10,  5,  6,  7])

In [ ]:
xyz[:]=20
xyz

array([20, 20, 20, 20])

In [ ]:
arr2=np.random.randn(3,3)
arr2

array([[-1.66139969,  0.41994658, -0.229722  ],
       [-0.48918928,  0.48288815,  0.35516217],
       [-0.27899205, -1.03356659,  0.70906335]])

In [ ]:
arr2[2]

array([-0.27899205, -1.03356659,  0.70906335])

In [ ]:
arr2[0][2]

-0.22972199896379616

In [ ]:
arr2[1][0]

-0.4891892773988018

In [ ]:
b=np.random.randn(4,2,3)
b

array([[[ 0.09605136, -0.8693187 ,  1.07532017],
        [-0.44155388,  2.23709769,  1.44999009]],

       [[-1.30220131, -0.39123318,  0.15772316],
        [ 0.18196532,  0.22673487,  0.72824929]],

       [[-0.74662009,  0.52870104,  0.81448139],
        [-1.4805683 , -1.1453813 ,  0.73514133]],

       [[-0.08906846,  0.17366419, -1.19462612],
        [-0.64612566,  0.4394859 ,  1.59061911]]])

In [ ]:
b[2]

array([[-0.74662009,  0.52870104,  0.81448139],
       [-1.4805683 , -1.1453813 ,  0.73514133]])

In [ ]:
b[1][1][0]

0.1819653190924289

In [ ]:
import numpy as np

names= np.array(['khizer','salah','khizer','saima','kamran','bob'])
data=np.random.randn(6,3)
names

array(['khizer', 'salah', 'khizer', 'saima', 'kamran', 'bob'], dtype='<U6')

In [ ]:
data

array([[ 1.13009413,  0.3214675 , -0.07809705, -0.098404  ],
       [ 1.73111528, -0.62564973,  0.07838584,  0.1105141 ],
       [-2.2468267 , -0.03299169,  1.8260334 , -0.73775685],
       [ 0.75370793,  0.26632618,  0.67390356,  2.24374585],
       [ 0.35883459, -0.18563112, -2.0589376 ,  1.10316559],
       [ 0.90812665, -0.91651304,  0.49210012,  0.65943691]])

In [ ]:
names=='khizer'

array([False, False,  True])

In [ ]:
data[names=='khizer']

array([[ 1.3777499 , -0.33645271,  0.7383552 ],
       [-1.81492363,  0.68163358,  1.21093737]])

In [ ]:
data[names=='khizer',1:]

array([[-0.33645271,  0.7383552 ],
       [ 0.68163358,  1.21093737]])

In [ ]:
data[names=='khizer',1]

array([-0.33645271,  0.68163358])

In [ ]:
data[names!='khizer']

array([[ 0.19743763, -1.23343301, -0.58326136],
       [-0.5139458 , -0.41331563,  0.13820884],
       [ 0.4278942 , -0.80598484,  0.17759764],
       [ 1.58798649,  0.82899228,  0.7107765 ]])

In [ ]:
import numpy as np

arr5=np.empty((13,4))
for i in range(13):
    arr5[i]=i

arr5

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.],
       [10., 10., 10., 10.],
       [11., 11., 11., 11.],
       [12., 12., 12., 12.]])

In [ ]:
arr6=np.arange(12).reshape(4,3)
arr6


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
arr=[1,2,3,4,5,6,7]
arr1=np.array(arr)

arr2=[7,5,6,4,3,2,1]
arr2=np.array(arr)

arr>arr2


array([False, False, False, False, False, False, False])

In [ ]:
import numpy as np
arr=[1,2,3,4,5,6,7]
arr1=np.array(arr)

arr2=[7,5,6,4,3,2,1]
arr2=np.array(arr)

arr<arr2

array([False, False, False, False, False, False, False])

In [ ]:
arr7=np.random.randn(6)

arr7

array([-0.43830547, -0.91194817, -0.79909865, -1.01731661,  0.29997151,
        1.14016467])

In [ ]:
arr8=np.random.randn(6,3)

arr8

array([[-1.11508611,  0.85723145, -1.56506793],
       [ 0.94631989,  0.76678574, -0.08075394],
       [-0.24916919, -0.99945925,  0.80553306],
       [ 1.49604953,  0.6018874 ,  0.23364961],
       [ 1.0413169 ,  0.44101766,  1.13310578],
       [ 0.89994991,  0.11071554,  1.06463516]])

In [ ]:
arr8.sort()
arr8

array([[-1.56506793, -1.11508611,  0.85723145],
       [-0.08075394,  0.76678574,  0.94631989],
       [-0.99945925, -0.24916919,  0.80553306],
       [ 0.23364961,  0.6018874 ,  1.49604953],
       [ 0.44101766,  1.0413169 ,  1.13310578],
       [ 0.11071554,  0.89994991,  1.06463516]])

In [ ]:
arr9=np.random.randn(6,3,4)

arr9

array([[[ 0.04156941,  0.92598363,  0.04199686,  2.48051278],
        [-0.20851137, -0.85063959, -0.65146889,  1.49508359],
        [ 1.31481127, -1.14059188,  0.1247995 ,  0.29600715]],

       [[-1.04026854,  0.85535981,  0.11649228,  0.19162784],
        [-0.23537361,  1.55351265, -0.61130285, -0.30290659],
        [ 0.0362329 ,  0.66341671,  0.55696195, -2.28589017]],

       [[ 0.60606682, -0.42867368,  1.16389877,  0.00367201],
        [ 1.21833238,  0.42804926,  1.14224268,  0.31490057],
        [-0.34869394,  2.26855962, -0.31591273,  0.62229699]],

       [[-1.06975737, -1.49033827,  0.26852994,  0.44509597],
        [ 0.8069727 ,  2.43377667,  0.57507646,  0.93280778],
        [-0.25555424,  0.48554442,  0.0599067 ,  1.92319775]],

       [[ 1.01626362, -0.4284739 ,  0.97945715, -0.87063815],
        [-0.09942253, -0.1078401 , -1.10729761, -1.43269883],
        [-0.02595441,  1.29365943,  1.33333924, -1.22950536]],

       [[ 1.01505696, -0.18675551,  0.76105891,  0.05164997]

In [ ]:
arr9.sort()
arr9

array([[[ 0.04156941,  0.04199686,  0.92598363,  2.48051278],
        [-0.85063959, -0.65146889, -0.20851137,  1.49508359],
        [-1.14059188,  0.1247995 ,  0.29600715,  1.31481127]],

       [[-1.04026854,  0.11649228,  0.19162784,  0.85535981],
        [-0.61130285, -0.30290659, -0.23537361,  1.55351265],
        [-2.28589017,  0.0362329 ,  0.55696195,  0.66341671]],

       [[-0.42867368,  0.00367201,  0.60606682,  1.16389877],
        [ 0.31490057,  0.42804926,  1.14224268,  1.21833238],
        [-0.34869394, -0.31591273,  0.62229699,  2.26855962]],

       [[-1.49033827, -1.06975737,  0.26852994,  0.44509597],
        [ 0.57507646,  0.8069727 ,  0.93280778,  2.43377667],
        [-0.25555424,  0.0599067 ,  0.48554442,  1.92319775]],

       [[-0.87063815, -0.4284739 ,  0.97945715,  1.01626362],
        [-1.43269883, -1.10729761, -0.1078401 , -0.09942253],
        [-1.22950536, -0.02595441,  1.29365943,  1.33333924]],

       [[-0.18675551,  0.05164997,  0.76105891,  1.01505696]

In [ ]:
arr10=np.random.randn(2,3,4,5,6,7)

arr10

array([[[[[[-1.88567992e+00, -1.78453790e+00, -3.02278118e-01, ...,
            -2.12463175e-01,  6.76498795e-01, -9.77211739e-01],
           [ 6.70936979e-01, -1.60814198e+00,  4.49083447e-01, ...,
            -2.37092333e-01,  1.21381018e+00,  1.22189350e+00],
           [-1.03779472e+00,  1.24728497e+00,  1.92200481e+00, ...,
             1.79859260e-01, -6.12005034e-01, -5.77194113e-01],
           [-3.90364211e-01, -2.70416097e+00,  1.28356617e-01, ...,
            -9.28920938e-01, -1.84890327e-01, -1.31210502e-01],
           [ 5.18382935e-01, -1.34223685e+00,  1.44209435e+00, ...,
             1.99903939e-01,  3.57871921e-01,  7.54183921e-01],
           [ 9.04427028e-01, -2.52598682e+00,  9.14027182e-01, ...,
             7.64122013e-01,  4.34623390e-01,  7.51852848e-01]],

          [[-9.03805984e-01,  7.76170878e-02, -1.04879525e+00, ...,
            -1.68837537e-01, -1.21053653e-01,  5.16217832e-01],
           [ 2.14993044e-01,  1.87308220e+00,  1.35643936e+00, ...,
      

In [ ]:
arr10.sort()
arr10

array([[[[[[-1.88567992e+00, -1.78453790e+00, -9.77211739e-01, ...,
            -3.02278118e-01, -2.12463175e-01,  6.76498795e-01],
           [-1.60814198e+00, -7.59512629e-01, -2.37092333e-01, ...,
             6.70936979e-01,  1.21381018e+00,  1.22189350e+00],
           [-1.03779472e+00, -6.12005034e-01, -5.77194113e-01, ...,
             1.24728497e+00,  1.92200481e+00,  2.13145448e+00],
           [-2.70416097e+00, -9.28920938e-01, -3.90364211e-01, ...,
            -1.31210502e-01,  1.28356617e-01,  1.34329112e-01],
           [-1.34223685e+00, -2.97051614e-01,  1.99903939e-01, ...,
             5.18382935e-01,  7.54183921e-01,  1.44209435e+00],
           [-2.52598682e+00, -7.85900880e-01,  4.34623390e-01, ...,
             7.64122013e-01,  9.04427028e-01,  9.14027182e-01]],

          [[-1.06269608e+00, -1.04879525e+00, -9.03805984e-01, ...,
            -1.21053653e-01,  7.76170878e-02,  5.16217832e-01],
           [-5.87149189e-01,  2.14993044e-01,  3.44581904e-01, ...,
      

In [ ]:
arr11=np.arange(10)
arr11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.save('arr12.npy',arr11)
np.load('arr12.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a= np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20],[30,40],[50,60]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a= np.array([[1,2,3],[4,5,6]])
b=np.array([[10,20],[30,40],[50,60]])
b

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
a.dot(b)

array([[220, 280],
       [490, 640]])

In [ ]:
np.dot(a,np.ones(3))

array([ 6., 15.])

In [ ]:
arr7.sort()
arr7

array([-1.01731661, -0.91194817, -0.79909865, -0.43830547,  0.29997151,
        1.14016467])

In [ ]:
import numpy as np
arr=[1,2,3,4,5,6,7]
arr1=np.array(arr)

arr2=[7,5,6,4,3,2,1]
arr2=np.array(arr)

arr==arr2

array([ True,  True,  True,  True,  True,  True,  True])

In [ ]:
abc=np.arange(10)
print(abc)
abc[6]


[0 1 2 3 4 5 6 7 8 9]


3

In [ ]:
abc=np.arange(10)
print(abc)
abc[2:5]

[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 4])

In [ ]:
import numpy as np


In [ ]:
arr2[:4]

array([1, 2, 3, 4])

In [ ]:
arr[4:]

[5, 6, 7]

In [ ]:
arr=np.arange(13)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2.ndim

2

In [ ]:
data.ndim

1

In [ ]:
arr1.ndim

1

In [ ]:
arr1=np.arange(101)
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr2=np.random.randn(1,3)
arr2

array([[-0.48593915, -1.87928766, -0.92090384]])

In [ ]:
arr3=[2,4,6,8,10]
arr3
data=np.array(arr3)
data

array([ 2,  4,  6,  8, 10])

In [ ]:
arr1.shape


(101,)

In [ ]:
arr2.shape

(1, 3)

In [ ]:
data.shape

(5,)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr2.dtype

dtype('float64')

In [ ]:
data.dtype

dtype('int64')

In [ ]:
a=np.random.randn(4,2,3)
a

array([[[-0.60293581, -0.43074885, -1.75690714],
        [-1.02557821,  1.76652178, -0.14508522]],

       [[-0.8497562 , -1.2939303 ,  1.5118243 ],
        [ 0.22280763,  1.01563612, -2.25826637]],

       [[ 1.83622983,  0.15174432,  0.84484499],
        [ 0.10202573, -0.93320313,  0.29935562]],

       [[-0.29648665, -1.23344884,  0.00977278],
        [-2.03329388, -0.05016996, -0.24028288]]])

In [ ]:
a.ndim

3

In [ ]:
a.shape

(4, 2, 3)

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.empty((2,3,4))

array([[[0.60293581, 0.43074885, 1.75690714, 1.02557821],
        [1.76652178, 0.14508522, 0.8497562 , 1.2939303 ],
        [1.5118243 , 0.22280763, 1.01563612, 2.25826637]],

       [[1.83622983, 0.15174432, 0.84484499, 0.10202573],
        [0.93320313, 0.29935562, 0.29648665, 1.23344884],
        [0.00977278, 2.03329388, 0.05016996, 0.24028288]]])

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
a*2


array([[[-1.20587162, -0.8614977 , -3.51381428],
        [-2.05115642,  3.53304355, -0.29017044]],

       [[-1.6995124 , -2.5878606 ,  3.02364859],
        [ 0.44561525,  2.03127225, -4.51653273]],

       [[ 3.67245967,  0.30348864,  1.68968998],
        [ 0.20405146, -1.86640627,  0.59871125]],

       [[-0.59297331, -2.46689768,  0.01954556],
        [-4.06658777, -0.10033992, -0.48056576]]])

In [ ]:
a+2

array([[[ 1.39706419,  1.56925115,  0.24309286],
        [ 0.97442179,  3.76652178,  1.85491478]],

       [[ 1.1502438 ,  0.7060697 ,  3.5118243 ],
        [ 2.22280763,  3.01563612, -0.25826637]],

       [[ 3.83622983,  2.15174432,  2.84484499],
        [ 2.10202573,  1.06679687,  2.29935562]],

       [[ 1.70351335,  0.76655116,  2.00977278],
        [-0.03329388,  1.94983004,  1.75971712]]])

In [ ]:
a+a

array([[[-1.20587162, -0.8614977 , -3.51381428],
        [-2.05115642,  3.53304355, -0.29017044]],

       [[-1.6995124 , -2.5878606 ,  3.02364859],
        [ 0.44561525,  2.03127225, -4.51653273]],

       [[ 3.67245967,  0.30348864,  1.68968998],
        [ 0.20405146, -1.86640627,  0.59871125]],

       [[-0.59297331, -2.46689768,  0.01954556],
        [-4.06658777, -0.10033992, -0.48056576]]])

In [ ]:
a-2

array([[[-2.60293581, -2.43074885, -3.75690714],
        [-3.02557821, -0.23347822, -2.14508522]],

       [[-2.8497562 , -3.2939303 , -0.4881757 ],
        [-1.77719237, -0.98436388, -4.25826637]],

       [[-0.16377017, -1.84825568, -1.15515501],
        [-1.89797427, -2.93320313, -1.70064438]],

       [[-2.29648665, -3.23344884, -1.99022722],
        [-4.03329388, -2.05016996, -2.24028288]]])

In [ ]:
a/2

array([[[-0.30146791, -0.21537443, -0.87845357],
        [-0.5127891 ,  0.88326089, -0.07254261]],

       [[-0.4248781 , -0.64696515,  0.75591215],
        [ 0.11140381,  0.50781806, -1.12913318]],

       [[ 0.91811492,  0.07587216,  0.4224225 ],
        [ 0.05101286, -0.46660157,  0.14967781]],

       [[-0.14824333, -0.61672442,  0.00488639],
        [-1.01664694, -0.02508498, -0.12014144]]])

In [ ]:
a**2

array([[[3.63531592e-01, 1.85544572e-01, 3.08672270e+00],
        [1.05181066e+00, 3.12059919e+00, 2.10497215e-02]],

       [[7.22085600e-01, 1.67425562e+00, 2.28561270e+00],
        [4.96432388e-02, 1.03151673e+00, 5.09976699e+00]],

       [[3.37174000e+00, 2.30263382e-02, 7.13763060e-01],
        [1.04092493e-02, 8.70868087e-01, 8.96137894e-02]],

       [[8.79043353e-02, 1.52139604e+00, 9.55072434e-05],
        [4.13428401e+00, 2.51702467e-03, 5.77358618e-02]]])

In [ ]:
a*a


array([[[3.63531592e-01, 1.85544572e-01, 3.08672270e+00],
        [1.05181066e+00, 3.12059919e+00, 2.10497215e-02]],

       [[7.22085600e-01, 1.67425562e+00, 2.28561270e+00],
        [4.96432388e-02, 1.03151673e+00, 5.09976699e+00]],

       [[3.37174000e+00, 2.30263382e-02, 7.13763060e-01],
        [1.04092493e-02, 8.70868087e-01, 8.96137894e-02]],

       [[8.79043353e-02, 1.52139604e+00, 9.55072434e-05],
        [4.13428401e+00, 2.51702467e-03, 5.77358618e-02]]])

In [ ]:
a/a

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a-a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
a**a

array([[    1,     4,    27],
       [  256,  3125, 46656]])